name: Compile

# This job triggers when opening/updating a pull request or merging to the main branch
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  # You can pin a particular version by replacing latest. E.g., @gamemaker/gm-cli@1.0.2
  GM_COMMAND: "@gamemaker/gm-cli@latest"

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      # Check out the git branch to build against
      - name: Checkout
        uses: actions/checkout@v6

      # Save a cache that can be reused between runs.
      # This will future runs faster, just like when you build the game locally
      - name: Cache
        uses: actions/cache@v5
        with:
          path: .gmcache
          key: ${{ runner.os }}-gmcache

      # ffmpeg is needed for linux: https://github.com/YoYoGames/GameMaker-Bugs/issues/4977
      - name: Load cached FFmpeg
        if: ${{ runner.os == 'Linux' }}
        id: cache-ffmpeg
        uses: actions/cache@v5
        with:
          path: ~/.local/share/ffmpeg-bin
          key: ${{ runner.os }}-ffmpeg-6.0.1

      - name: Install FFmpeg if not cached
        if: ${{ runner.os == 'Linux' && steps.cache-ffmpeg.outputs.cache-hit != 'true' }}
        run: |
          VERSION=6.0.1
          RELEASE_NAME=ffmpeg-${VERSION}-amd64-static
          mkdir -p ~/.local/share/ffmpeg-bin
          wget --timeout=8 --tries=10 https://www.johnvansickle.com/ffmpeg/old-releases/${RELEASE_NAME}.tar.xz
          tar -xf ${RELEASE_NAME}.tar.xz
          mv ${RELEASE_NAME}/ffmpeg ${RELEASE_NAME}/ffprobe ~/.local/share/ffmpeg-bin/
          rm -rf ${RELEASE_NAME} ${RELEASE_NAME}.tar.xz

      # Make sure the cached binaries are available to subsequent steps
      - name: Add FFmpeg to PATH
        if: ${{ runner.os == 'Linux' }}
        run: echo "$HOME/.local/share/ffmpeg-bin" >> $GITHUB_PATH

      # You can create an access token at https://gamemaker.io/en/account/access-keys
      # Then, in github, set a Repository Secret named GAMEMAKER_PAT with that value
      # in you repository Settings/Secrets and Varibles/Actions/New repository secret
      - run: npx "$GM_COMMAND" login "$GAMEMAKER_PAT"
        if: ${{ env.GAMEMAKER_PAT != '' }}

      # "Test compile" the game. Does not produce a bundle, but rather checks that it
      # possible to compile the game
      - run: npx "$GM_COMMAND" compile
        env:
          NO_COLOR: 1
